#!/bin/sh
if [ $# != 2 ]; then
  echo "Usage: mkglick <glick file> <ext2 image name> "
  exit 1
fi
GLICK_FILE=$1
EXT2_IMAGE=$2

DIR=`mktemp -d`
cp $EXT2_IMAGE $DIR/image
(cd $DIR; ld -r -b binary -o image.o image)
objcopy --rename-section .data=.rodata,alloc,load,readonly,data,cont $DIR/image.o
# Dynamic ext2fs
EXT2FS_LIB=`pkg-config --libs ext2fs`
# Static ext2fs
EXT2FS_LIB="/usr/lib/libext2fs.a /usr/lib/libcom_err.a" 
gcc header.a $DIR/image.o $EXT2FS_LIB `pkg-config --libs fuse` -o $GLICK_FILE
rm -rf $DIR
strip $GLICK_FILE
